-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
--  ◈ ENVIRONMENT VARIABLES (AUTOGENERATED)
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

hl.env("NIXOS_OZONE_WL", "1")
-- Required for Electron/Spotify/etc when the login session does not export it
hl.env("DBUS_SESSION_BUS_ADDRESS", "unix:path=/run/user/1000/bus")
hl.env("XDG_PICTURES_DIR", "/home/ndyar/Pictures")
hl.env("XDG_VIDEOS_DIR", "/home/ndyar/Videos")
hl.env("WALLPAPER_DIR", "/home/ndyar/Pictures/Wallpapers")
hl.env("SCRIPT_DIR", "/home/ndyar/.config/hypr/scripts")

-- Hardware Injections

