-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
--  ◈ SETTINGS (AUTOGENERATED FROM SETTINGS.JSON)
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

hl.config({
    general = {
        border_size = 2,
        gaps_in = 4,
        gaps_out = 4,
        float_gaps = 6,
        resize_on_border = true,
        extend_border_grab_area = 30,
    },

    decoration = {
        rounding = 4,
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        blur = {
            enabled = true,
            size = 30,
            passes = 5,
            new_optimizations = true,
            xray = true,
        },
        shadow = {
            enabled = false,
        },
    },

    input = {
        kb_layout = "us",
        kb_options = "grp:alt_shift_toggle",

        touchpad = {
            natural_scroll = true,
        },
    },

    cursor = {
        no_warps = true,
    },

    misc = {
        font_family = "JetBrains Mono",
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        force_default_wallpaper = 0,
    },

    ecosystem = {
        no_update_news = true,
        no_donation_nag = true,
    },

    animations = {
        enabled = true,
    },

    -- Prevents blurry/pixelated XWayland apps (Spotify, etc.) on fractional scale
    xwayland = {
        force_zero_scaling = true,
    },
})

-- Animations must use hl.curve / hl.animation (hl.config only accepts animations.enabled)
hl.curve("myBezier", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })

hl.animation({ leaf = "windows",              enabled = true, speed = 5, bezier = "myBezier", style = "popin 80%" })
hl.animation({ leaf = "windowsIn",            enabled = true, speed = 5, bezier = "myBezier", style = "popin 80%" })
-- Keep fadeOut enabled: disabling it makes close look instant (opacity jumps to 0).
-- Foot still tends to clear its buffer early; matching fadeOut+windowsOut speed helps.
hl.animation({ leaf = "windowsOut",           enabled = true, speed = 5, bezier = "myBezier", style = "popin 80%" })
hl.animation({ leaf = "fade",                 enabled = true, speed = 5, bezier = "myBezier" })
hl.animation({ leaf = "fadeIn",               enabled = true, speed = 5, bezier = "myBezier" })
hl.animation({ leaf = "fadeOut",              enabled = true, speed = 5, bezier = "myBezier" })
hl.animation({ leaf = "layers",               enabled = true, speed = 5, bezier = "myBezier", style = "fade" })
hl.animation({ leaf = "layersIn",             enabled = true, speed = 5, bezier = "myBezier", style = "fade" })
hl.animation({ leaf = "layersOut",            enabled = true, speed = 5, bezier = "myBezier", style = "fade" })
hl.animation({ leaf = "workspaces",           enabled = true, speed = 5, bezier = "myBezier", style = "slide" })
hl.animation({ leaf = "specialWorkspaceIn",   enabled = true, speed = 5, bezier = "myBezier", style = "fade" })
hl.animation({ leaf = "specialWorkspaceOut",  enabled = true, speed = 5, bezier = "myBezier", style = "fade" })

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

